### ISSUE TITLE
Code is out of sync with the latest release of the library

### ISSUE THREAD

**Issue by ngupta23** [matrix-profile-foundation/article-matrix-profile-intro#3]
I am trying to evaluate this library and it seems like the code in the following notebook is out of sync with the latest library version.

```article-matrix-profile-intro.ipynb```

The following modules are no longer in these locations

```
from matrixprofile.matrixProfile import stomp
from matrixprofile.motifs import motifs
from matrixprofile.discords import discords
```

**Comment by tylerwmarrs** [comment]
Thank you for bringing this to our attention. Yes, it is outdated at this point and I plan to update this code. In the mean time, the code documentation is a little more thorough than this article. Please check out the documentation here https://matrixprofile.docs.matrixprofile.org/index.html

The get started section should be a good starting point. If you would like to update this code, please feel free to submit a pull request.

**Comment by ngupta23** [comment]
Thanks for your response. It looks like this is still in active development with files and modules being moved around. Would you have a timeline for when the code would be relatively stable? Thanks!

**Comment by tylerwmarrs** [comment]
Yes, the library "matrixprofile" is in active development. However, the old library, owned by Target, "matrixprofile-ts", is not actively developed or maintained by us. I originally contributed many codes to the Target repository and used that library for this article. To avoid confusion, I should update the code base to reflect what we use.

In regards to files moving - this library is a 100% re-write and will never match the original "matrixprofile-ts" API. The "matrixprofile" library will not have files moved around or breaking changes. Any version less than 1.x.x will have the same API. At this point the focus is on features and bug fixes that come up.

**Comment by ngupta23** [comment]
Got it. Thanks. Yes, it would be great to update the code in the repo as it is linked from the Towards Data Science article.

**Comment by tylerwmarrs** [comment]
KDD article? You mean Towards Data Science (TDS)?

**Comment by tylerwmarrs** [comment]
https://github.com/matrix-profile-foundation/article-matrix-profile-intro/commit/ffba0c683427d4399ab28d02450e12fe21f84431

**Comment by ngupta23** [comment]
Yes, fixed now.
